### ISSUE TITLE
Using Netlink-taskstats in GPL open source tool?

### ISSUE THREAD

**Issue by tanelpoder** [prod-feng/Netlink-taskstats#1]
Hi, as the source code doesn't have license info, do you allow using this Netlink-taskstats code as a library in an open source (GPL) Linux performance tool that I'm building? (with proper credits & attribution of course). 

The tool I'm building is like a more flexible "top" that allows going deeper into thread states than the typical tools do: 

Example output is here: https://tp.dev/psnapper

Thanks!

**Comment by tanelpoder** [comment]
I ended up using a different library.

**Comment by prod-feng** [comment]
Sure, please use it. I just missed your message. 

Best

**Comment by tanelpoder** [comment]
Cool, thanks!
